vim.keymap.set('n', '<leader>gs', vim.cmd.Git)
vim.keymap.set('n', "<leader>gA", ":Git add .<cr>", {desc = "[G]it Add [A]ll"})
vim.keymap.set('n', "<leader>ga", ":Git add", {desc = "[G]it Add"})
vim.keymap.set('n', "<leader>gc", ":Git commit", {desc = "[G]it Commit"})
vim.keymap.set('n', "<leader>gp", ":Git push origin main", {desc = "[G]it Push"})
